apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kafka
  labels:
    app: spring-boot-kafka
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8080
      nodePort: 30080
  selector:
    app: spring-boot-kafka

